### PR TITLE
Rename package to `epidatpy`

### LINKED ISSUE #13: Rename package to `epidatpy`
See https://github.com/cmu-delphi/delphi-epidata-r/issues/31.  The R package rename is currently in progress.  The Python package is currently not being worked on.

Following [the renaming process in Logan's comment](https://github.com/cmu-delphi/epidatr/issues/31#issuecomment-1195732206)

- [x] #16 
- [x] Ping relevant channels with a notice.
- [x] Create branch holding the old name package: [`delphi_epidata-before-rename`](https://github.com/cmu-delphi/delphi-epidata-py/tree/delphi_epidata-before-rename).
- [ ] Pre-switch anything in production using delphi.epidata to this branch. [removed irrelevant epidatr stuff] Schedule transition back to the main branch + renaming [delphi_epidata -> epidatpy] for these things.
- [x] #17 
- [ ] #15
- [ ] Downstream, perform the scheduled switches to rely on main branch & epidatpy package name.

### PR DESCRIPTION
**Pull request by dshemetov**
Closes #13.

Replaced all instances of `delphi_epidata` with `epidatpy` in
- source
- documentation
- tests
- installation files

Can import package and use it. CI should pass.

### CODE REVIEW

**Comment by brookslogan** [comment]
My familiarity with Python is limited and stale, so please bear with me.  I'm testing out the first README.md commands, encountered trouble.  For the first one:
```sh
python -m venv ../venv-epidatpy
../venv-epidatpy/bin/pip install --upgrade pip
#> [output elided]
../venv-epidatpy/bin/python --version
#> Python 3.10.5
../venv-epidatpy/bin/pip --version
#> pip 22.2.2 from /home/fullname/files/tooling/venv-epidatpy/lib64/python3.10/site-packages/pip (python 3.10)
../venv-epidatpy/bin/pip install -e "git+https://github.com/cmu-delphi/epidatpy.git"
#> ERROR: Could not detect requirement name for 'git+https://github.com/cmu-delphi/epidatpy.git', please specify one with #egg=your_package_name
```
and the second one (for the pre-rename version) also has the same type of message.

**Comment by brookslogan** [comment]
Is this an issue with my configuration, or does it mean that the install string needs an egg setting suffix?

**Comment by brookslogan** [comment]
- Changes that were made look fine to me.
- Potentially missing changes?
  - README.md: [pypi-image], [pypi-url], [docs-image], [docs-url]
  -  index.rst: 4x references to "delphi-epidata".  One is straightforward... link to github should be to epidatpy.  The pypi links and installation commands... I assume that these are referring to the old client, right?  And that we are making a new pypi package for the new one?

**Comment by dshemetov** [comment]
So the current docs (README + index.rst) are written as if this package was already on PyPI and all the documentation sites existed. I figure we will make those before release, so the documentation is accurate.

Otherwise, I addressed your comments: README is updated, index.rst is updated, and I added an `#egg#` parameter (I thought you could get away without it, but I think not in pip with the -e flag).

**Comment by brookslogan** [comment]
Some notes:
- In `index.rst`: https://cmu-delphi.github.io/delphi-epidata/api is a broken link, but not due to a missing rename -> epidatpy.  We must have broken it via updates to the API docs, outside this repo.  So might want to file a separate issue.
- The first install command still fails for me, but I assume that merging this PR will fix it.
- The second install command seems to succeed for me both with `#egg=delphi_epidata` and `#egg=delphi-epidata`, but I can only `pip uninstall delphi-epidata`, not `pip uninstall delphi_epidata`.  I don't know enough about Python packge dev to know if this is an issue.  I assume since it seems to install successfully in either case, and we're migrating away, this isn't something to worry about.
- File diffs look good.

I think this looks fine to merge, but leave hitting the button to you, in case one of the above looks like it actually requires changes.

**Comment by dshemetov** [comment]
Good catch on the broken link! I'll fix and the first line should work.

As for your third point, this is just [one of those strange Python things](https://stackoverflow.com/questions/54597212/using-hyphen-dash-in-python-repository-name-and-package-name), where the PyPI distribution name is `delphi-epidata` and that's what you call with `pip`, but `delphi_epidata` is the actual package name. So uninstalling should reference the first. I guess that `#egg=delphi_epidata` works because the package folder is `delphi_epidata`. Not sure why `#egg=delphi-epidata` works, since that's not anywhere in the package metadata 🤷 .

**Comment by brookslogan** [comment]
First install command does indeed appear to work after the merge!

Thanks; I couldn't quickly find anything explaining which of the several names the `#egg` thing should use.  Somehow within the top level of the repo directory, I have an untracked `src` folder containing a single subdirectory `delphi-epidata` with delphi_epidata-before-rename checked out.  Not sure if that's related to whatever thing made `#egg=delphi-epidata` work.

**Pull request merged**
